#include "improvementdata.h"

const ImprovementData improvementdata[]={
//id						name			res,	buygold,	upgold,	sellgold
{/*IMPROVEMENT_NONE,*/		nullptr,		0,		0,			0,		0},
{/*IMPROVEMENT_GRANARY,*/	"Granary",		150,	150,		2,		100},
{/*IMPROVEMENT_BARRACKS,*/	"Barracks",		250,	250,		4,		200},
{/*IMPROVEMENT_CITYWALLS,*/	"City Walls",	350,	350,		5,		300},
{/*IMPROVEMENT_MARKET,*/	"Market",		500,	500,		8,		400},
{/*IMPROVEMENT_BANK,*/		"Bank",			500,	500,		8,		400},
{/*IMPROVEMENT_FACTORY,*/	"Factory",		500,	500,		8,		400},
{/*IMPROVEMENT_AQUEDUCT,*/	"Aqueduct",		500,	500,		5,		400}
};

const BuildingXref buildingxref[]={
//id						type						build
{/*BUILDING_NONE,*/			BUILDINGTYPE_NONE,			0},
{/*BUILDING_SETTLER,*/		BUILDINGTYPE_UNIT,			UNITTYPE_SETTLER},
{/*BUILDING_MILITIA,*/		BUILDINGTYPE_UNIT,			UNITTYPE_MILITIA},
{/*BUILDING_ARCHER,*/		BUILDINGTYPE_UNIT,			UNITTYPE_ARCHER},
{/*BUILDING_TRIREME,*/		BUILDINGTYPE_UNIT,			UNITTYPE_TRIREME},
{/*BUILDING_HORSEMAN,*/		BUILDINGTYPE_UNIT,			UNITTYPE_HORSEMAN},
{/*BUILDING_KNIGHT,*/		BUILDINGTYPE_UNIT,			UNITTYPE_KNIGHT},
{/*BUILDING_SAIL,*/			BUILDINGTYPE_UNIT,			UNITTYPE_SAIL},
{/*BUILDING_GRANARY,*/		BUILDINGTYPE_IMPROVEMENT,	IMPROVEMENT_GRANARY},
{/*BUILDING_BARRACKS,*/		BUILDINGTYPE_IMPROVEMENT,	IMPROVEMENT_BARRACKS},
{/*BUILDING_CITYWALLS,*/	BUILDINGTYPE_IMPROVEMENT,	IMPROVEMENT_CITYWALLS},
{/*BUILDING_MARKET,*/		BUILDINGTYPE_IMPROVEMENT,	IMPROVEMENT_MARKET},
{/*BUILDING_FACTOR,*/		BUILDINGTYPE_IMPROVEMENT,	IMPROVEMENT_FACTORY},
{/*BUILDING_BANK,*/			BUILDINGTYPE_IMPROVEMENT,	IMPROVEMENT_BANK},
{/*BUILDING_AQUEDUCT,*/		BUILDINGTYPE_IMPROVEMENT,	IMPROVEMENT_AQUEDUCT}
};
